.build: &build
 stage: build
 script:
 - mkdir BUILD
 - cd BUILD
 - cmake -DCMAKE_INSTALL_PREFIX=../INSTALL ..
 - cmake --build . --target install
 artifacts:
  paths:
  - BUILD
  - INSTALL
  expire_in: 6h

.test: &test
 script:
 - cd BUILD
 - VERBOSE=1 ctest --output-on-failure

.deploy: &deploy
 stage: deploy
 script:
 - mv * /mnt
 - mv /mnt/INSTALL/* .
 artifacts:
  name: "$CI_PROJECT_PATH_SLUG-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  untracked: true
 only:
 - master



.ubuntu16: &ubuntu16
 image: ubuntu:16.04
 before_script:
 - apt-get update
 - >
  apt-get install -y
  cmake
  g++
  libboost-filesystem-dev
  libboost-iostreams-dev
  libeigen3-dev
  libopencv-dev
  libqt5opengl5-dev
  libqt5svg5-dev
build-ubuntu16:
 <<: *build
 <<: *ubuntu16
test-ubuntu16:
 <<: *test
 <<: *ubuntu16
 dependencies:
 - build-ubuntu16
deploy-ubuntu16:
 <<: *deploy
 dependencies:
 - build-ubuntu16

.ubuntu18: &ubuntu18
 image: ubuntu:18.04
 before_script:
 - apt-get update
 - >
  apt-get install -y
  cmake
  g++
  libboost-filesystem-dev
  libboost-iostreams-dev
  libeigen3-dev
  libopencv-dev
  libqt5opengl5-dev
  libqt5svg5-dev
 variables:
  DEBIAN_FRONTEND: noninteractive
build-ubuntu18:
 <<: *build
 <<: *ubuntu18
test-ubuntu18:
 <<: *test
 <<: *ubuntu18
 dependencies:
 - build-ubuntu18
deploy-ubuntu18:
 <<: *deploy
 dependencies:
 - build-ubuntu18

.ros16: &ros16
 image: osrf/ros:kinetic-desktop-full
build-ros16:
 <<: *build
 <<: *ros16
test-ros16:
 <<: *test
 <<: *ros16
 dependencies:
 - build-ros16
deploy-ros16:
 <<: *deploy
 dependencies:
 - build-ros16

.ros18: &ros18
 image: osrf/ros:melodic-desktop-full
 before_script:
 - apt-get update
 - >
  apt-get install -y
  doxygen
  libqt5svg5-dev
build-ros18:
 <<: *build
 <<: *ros18
test-ros18:
 <<: *test
 <<: *ros18
 dependencies:
 - build-ros18
deploy-ros18:
 <<: *deploy
 dependencies:
 - build-ros18

